### ISSUE TITLE
TypeError: param.trim is not a function

### ISSUE THREAD

**Issue by varundeva** [paytm/paytm-pg-node-sdk-sample#1]
```
TypeError: param.trim is not a function
    at Function.isEmptyOrNull (/home/freesv/Desktop/BUDonation/node_modules/paytm-pg-node-sdk/dist/com/paytm/pg/utils/CommonUtil.js:71:81)
    at new PaymentDetailBuilder (/home/freesv/Desktop/BUDonation/node_modules/paytm-pg-node-sdk/dist/com/paytm/merchant/models/PaymentDetail.js:201:36)
    at app.post (/home/freesv/Desktop/BUDonation/routes.js:38:36)
    at Layer.handle [as handle_request] (/home/freesv/Desktop/BUDonation/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/freesv/Desktop/BUDonation/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/freesv/Desktop/BUDonation/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/freesv/Desktop/BUDonation/node_modules/express/lib/router/layer.js:95:5)
    at /home/freesv/Desktop/BUDonation/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/freesv/Desktop/BUDonation/node_modules/express/lib/router/index.js:335:12)
    at next (/home/freesv/Desktop/BUDonation/node_modules/express/lib/router/index.js:275:10)
```

**Comment by mxvsh** [comment]
any fix?

**Comment by varundeva** [comment]
No
This repo is not maintained
Try to get other references :(
